/*
 * Host-like WEB APIs with Swagger.
 * This is a practice to make host-like WEB APIs with Swagger generated code. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akahane.yasuhiko@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.sv_b.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Sbz003bReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-03-19T21:46:58.461691+09:00[Asia/Tokyo]")
public class Sbz003bReq {
  @SerializedName("reqItem1")
  private String reqItem1 = null;

  public Sbz003bReq reqItem1(String reqItem1) {
    this.reqItem1 = reqItem1;
    return this;
  }

   /**
   * Get reqItem1
   * @return reqItem1
  **/
  @Schema(example = "hoga", required = true, description = "")
  public String getReqItem1() {
    return reqItem1;
  }

  public void setReqItem1(String reqItem1) {
    this.reqItem1 = reqItem1;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sbz003bReq sbz003bReq = (Sbz003bReq) o;
    return Objects.equals(this.reqItem1, sbz003bReq.reqItem1);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reqItem1);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sbz003bReq {\n");
    
    sb.append("    reqItem1: ").append(toIndentedString(reqItem1)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
