/*
 * Host-like WEB APIs with Swagger.
 * This is a practice to make host-like WEB APIs with Swagger generated code. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akahane.yasuhiko@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.sv_c.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Sbz003cReq
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2021-01-01T02:13:18.647Z[GMT]")
public class Sbz003cReq {
  @SerializedName("reqItem2")
  private String reqItem2 = null;

  public Sbz003cReq reqItem2(String reqItem2) {
    this.reqItem2 = reqItem2;
    return this;
  }

   /**
   * Get reqItem2
   * @return reqItem2
  **/
  @Schema(example = "XXXX0000", required = true, description = "")
  public String getReqItem2() {
    return reqItem2;
  }

  public void setReqItem2(String reqItem2) {
    this.reqItem2 = reqItem2;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Sbz003cReq sbz003cReq = (Sbz003cReq) o;
    return Objects.equals(this.reqItem2, sbz003cReq.reqItem2);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reqItem2);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Sbz003cReq {\n");
    
    sb.append("    reqItem2: ").append(toIndentedString(reqItem2)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
