/*
 * Host-like WEB APIs with Swagger.
 * This is a practice to make host-like WEB APIs with Swagger generated code.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: akahane.yasuhiko@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Ignore;
import org.junit.Test;
import io.swagger.client.sv_b.ApiException;
import io.swagger.client.sv_c.api.SampleBizSvCApi;
import io.swagger.client.sv_c.model.InlineResponse200;
import io.swagger.client.sv_c.model.Sbz003cReq;

/**
 * API tests for SampleBizSvCApi
 */
@Ignore
public class SampleBizSvCApiTest {

    private final SampleBizSvCApi api = new SampleBizSvCApi();

    /**
     * The API return various items by status code.
     *
     *
     *
     * @throws ApiException
     *          if the Api call fails
     * @throws io.swagger.client.sv_c.ApiException
     */
    @Test
    public void sbz003Test() throws ApiException, io.swagger.client.sv_c.ApiException {
        Sbz003cReq body = null;
        InlineResponse200 response = api.sbz003(body);

        // TODO: test validations
    }
}
